### ISSUE TITLE
missing. 'create' parameter in client.authenticateEmail

### ISSUE THREAD

**Issue by mshanak** [heroiclabs/nakama-cocos2d-x-javascript#11]
Am using this plugin with cocos creator, but I didn't find a way to create a registration page since the 'create' parameter is missing when I use the `client.authenticateEmail`.

in the documentation page, the example shows a creat parameter,  I think this library is outdated.

![Screen Shot 2021-03-13 at 10 33 29 AM](https://user-images.githubusercontent.com/964266/111024499-cc1bf380-83e7-11eb-84e9-a48e32f9dc5a.png)

**Comment by lugehorsam** [comment]
Hey @mshanak this is now resolved in the latest release: https://github.com/heroiclabs/nakama-cocos2d-x-javascript/releases/tag/v2.1.0
