### ISSUE TITLE
ANDROID SSL connection problem

### ISSUE THREAD

**Issue by jhyoo2** [heroiclabs/nakama-cocos2d-x-javascript#15]
Hi guys. I have a new problem, so please share.

This issue is a problem that works perfectly in the web version but does not work in AOS.

First, my development environment looks like this:

cocos creator: 3.5.1 version (there was the same issue in 3.3.2)
nakama : 3.11.0+c820042d
server os: windows 10
port : 7350

First, I am connecting to the domain. I'm using the certificate I got from the chamelio.co.kr domain.

However, this works fine in the web version, but does not work when built with AOS.

The error message called from the server is as follows

slot_nakama-nakama-1 | {"level":"info","ts":"2022-06-08T09:11:07.188Z","caller":"http/server.go:3197","msg":"http: TLS handshake error from 172.19.0.1:44478: remote error: tls: unknown certificate"}

May I know how to solve this?

**Comment by jhyoo2** [comment]
If you don't use ssl, it works perfectly, and the web version works perfectly, but AOS is the only problem.

**Comment by mofirouz** [comment]
Looks like you've misconfigured your proxy or the client, or the certificate based on the error message:

```remote error: tls: unknown certificate"```

This isn't an issue on the client SDK - something misconfigured on your end. If you'd like to discuss further, please open a forum post. Thanks.
