### ISSUE TITLE
authenticateCustom() is broken in IOS

### ISSUE THREAD

**Issue by pranav8gitlab** [heroiclabs/nakama-cocos2d-x-javascript#7]
I am using cocos js client and its working fine on android but on ios simulator its giving error `Attempted to assign to readonly property in authenticateCustom()` . There are not logs on socket level as well on server. Error is coming from this part of code `new Promise(function (_, reject) { return setTimeout(reject, _this.configuration.timeoutMs, "Request timed out."); }` 

**Steps to reproduce:**
1) build a project using cocos creator and nakama `authenticateCustom()`.
2) run on IOS Simulator or device.

**Result:**  `authenticateCustom()` fails with error `Attempted to assign to readonly property`. Same code will run well on all other platforms.

**Expected Result:** `authenticateCustom()` should return success as in all other platforms.

**Comment by lugehorsam** [comment]
@pranav8gitlab could you try the latest commit and let me know how that goes? I wasn't able to reproduce your issue, but I thought updating the Javascript to the latest version would be a good start.

**Comment by pranav8gitlab** [comment]
Hi I did tried to update the nakama sdk but still got the same error. I have made a sample project and getting the same error in it so sharing it with you. [cocos project](https://drive.google.com/file/d/1yVlzhuu_WOfZRYxlfdWzGk7PH9HC9OKk/view?usp=sharing)  . IOS project is already there under build/jsb-link/frameworks/runtime-src (it is with my debug server values) and to change the server variables use assets/Login.ts . You should be getting these logs when you run project on  IOS Simulator .   Check for second last log.

```
JS: Create unpacker 0ea3dbfa0 for 60AwGqM1dKELCGhPAR+jK6
libpng warning: iCCP: known incorrect sRGB profile
JS: Cocos Creator v2.3.4
JS: LoadScene e9OzVWbcZK+7eYx+l7U7hn: 76.63499999999999ms
JS: InitScene: 4.75ms
JS: AttachPersist: 0.4679999999999609ms
JS: AutoRelease: 0.22199999999998ms
JS: Destroy: 0.007000000000061846ms
JS: Activate: 71.731ms
JS: Success to load scene: db://assets/test.fire
JS:  client made 
JS:  auth error TypeError: Attempted to assign to readonly property.
JS:  auth error {}
```

May be I am missing something here. Incase anything else is required from my side then do let me know.

**Comment by pranav8gitlab** [comment]
> @pranav8gitlab Once #8 is merged, could you try the latest commit and let me know how that goes? I wasn't able to reproduce your issue, but I thought updating the Javascript to the latest version would be a good start.

Hi @lugehorsam   , were you able to reproduce it at your end through my sample project? If anything else is required from my side then do let me know.

**Comment by lugehorsam** [comment]
Hey @pranav8gitlab, still not quite able to reproduce it. Here are the logs I see when I run your project from Cocos Creator and clicking on the "Simulator" dropdown next to the Play button in the Cocos Creator GUI:

<img width="804" alt="Screen Shot 2020-09-18 at 1 07 52 PM" src="https://user-images.githubusercontent.com/3965481/93625563-2a739680-f9b0-11ea-9db7-b84fb4d4f230.png">

**Comment by pranav8gitlab** [comment]
> Hey @pranav8gitlab, still not quite able to reproduce it. Here are the logs I see when I run your project from Cocos Creator after clicking on the "Simulator" dropdown next to the Play button in the Cocos Creator GUI:
> 
> <img alt="Screen Shot 2020-09-18 at 1 07 52 PM" width="804" src="https://user-images.githubusercontent.com/3965481/93625563-2a739680-f9b0-11ea-9db7-b84fb4d4f230.png">

Hi , I know its kind of weird but from same project i am still getting the same error. I tried to make a local server on 127.0.0.1 and port 7350 as suggested in nakama tutorial and but still the same error. I had uploaded a video of how I am running (steps are same as suggested by you but still uploaded it) [video link](https://drive.google.com/file/d/11J9MDaGskXs_riPoVWUlSc8fHoCWpOqM/view?usp=sharing) . What is your xcode version  ? mine is 11.4 and os is 10.15.4 , What else can we try to understand the issue from here? Also I modified the code little bit and printed the error on screen only , here is updated code [update project (just ui changes)](https://drive.google.com/file/d/1NJEbIJ8Tx0B0YR5dpRfj5KlywZZR-Ib9/view?usp=sharing)

**Comment by pranav8gitlab** [comment]
Hi guys , any update on this?

**Comment by lugehorsam** [comment]
@pranav8gitlab I am able to reproduce your issue and am aiming to fix this today.

**Comment by pranav8gitlab** [comment]
hi @lugehorsam , any progress on this?

**Comment by lugehorsam** [comment]
@pranav8gitlab this issue should now be resolved by https://github.com/heroiclabs/nakama-cocos2d-x-javascript/commit/2a061ce42cc0a719d6b2f1306c3efcc9f758bfcc

**Comment by pranav8gitlab** [comment]
Hi @lugehorsam now I am  getting this error in return of authenticateCustom on IOS Simulator

`jsb: ERROR: File /Users/Project/build/jsb-default/frameworks/cocos2d-x/cocos/scripting/js-bindings/manual/jsb_xmlhttprequest.cpp: Line: 1096, Function: XMLHttpRequest_setResponseType
The response type isn't supported![ERROR] Failed to invoke XMLHttpRequest_setResponseType, location: /Users/Project/build/jsb-default/frameworks/cocos2d-x/cocos/scripting/js-bindings/manual/jsb_xmlhttprequest.cpp:1104
2020-12-01 12:21:34.960571+0530 Project-mobile[15052:359627] [] nw_socket_handle_socket_event [C5:2] Socket SO_ERROR [61: Connection refused]
2020-12-01 12:21:34.961738+0530 Project-mobile[15052:359627] Connection 5: received failure notification
2020-12-01 12:21:34.961883+0530 Project-mobile[15052:359627] Connection 5: failed to connect 1:61, reason -1
2020-12-01 12:21:34.962660+0530 Project-mobile[15052:359627] Connection 5: encountered error(1:61)
2020-12-01 12:21:34.966333+0530 Project-mobile[15052:359627] Task <44468F5E-5723-4321-A80B-43ADF0DFFAAE>.<0> HTTP load failed, 0/0 bytes (error code: -1004 [1:61])
2020-12-01 12:21:34.967048+0530 Project-mobile[15052:359582] NSURLConnection finished with error - code -1004
Response failed, error buffer: Could not connect to the server.`

**Comment by pranav8gitlab** [comment]
Hi @lugehorsam did u get a chance to look into it? same library is working fine on android.
