### ISSUE TITLE
Error in authenticateCustom() on IOS

### ISSUE THREAD

**Issue by pranav8gitlab** [heroiclabs/nakama-cocos2d-x-javascript#9]
Hi  I am getting this error in return of authenticateCustom on IOS Simulator , on Android its working fine . I am using latest version of nakama library and  Cocos creator version 2.4.3 . 

`jsb: ERROR: File /Users/Project/build/jsb-default/frameworks/cocos2d-x/cocos/scripting/js-bindings/manual/jsb_xmlhttprequest.cpp: Line: 1096, Function: XMLHttpRequest_setResponseType The response type isn't supported![ERROR] Failed to invoke XMLHttpRequest_setResponseType, location: /Users/Project/build/jsb-default/frameworks/cocos2d-x/cocos/scripting/js-bindings/manual/jsb_xmlhttprequest.cpp:1104 2020-12-01 12:21:34.960571+0530 Project-mobile[15052:359627] [] nw_socket_handle_socket_event [C5:2] Socket SO_ERROR [61: Connection refused] 2020-12-01 12:21:34.961738+0530 Project-mobile[15052:359627] Connection 5: received failure notification 2020-12-01 12:21:34.961883+0530 Project-mobile[15052:359627] Connection 5: failed to connect 1:61, reason -1 2020-12-01 12:21:34.962660+0530 Project-mobile[15052:359627] Connection 5: encountered error(1:61) 2020-12-01 12:21:34.966333+0530 Project-mobile[15052:359627] Task <44468F5E-5723-4321-A80B-43ADF0DFFAAE>.<0> HTTP load failed, 0/0 bytes (error code: -1004 [1:61]) 2020-12-01 12:21:34.967048+0530 Project-mobile[15052:359582] NSURLConnection finished with error - code -1004 Response failed, error buffer: Could not connect to the server.`

**Comment by lugehorsam** [comment]
@pranav8gitlab I've resolved your issue with https://github.com/heroiclabs/nakama-cocos2d-x-javascript/commit/0bf528782926e6906069a75cbe7b5bd0ccf80c63 

Please note that the signature for authentication methods has changed slightly (see example in README.md) so you'll need to tweak that.
